import type { StyleProp, ViewStyle } from "react-native";
import type { AnimatedStyle } from "react-native-reanimated";
import React, { useEffect, useState } from "react";
import {
  ActivityIndicator,
  Keyboard,
  Platform,
  RefreshControl,
  Text,
  View,
} from "react-native";
import Animated, {
  Easing,
  FadeIn,
  FadeInLeft,
  FadeInRight,
  FadeInUp,
  FadeOut,
  FadeOutLeft,
  FadeOutRight,
  FadeOutUp,
  LinearTransition,
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from "react-native-reanimated";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { SplashScreen, Stack, useRouter } from "expo-router";
import { TZDate } from "@date-fns/tz";
import Feather from "@expo/vector-icons/Feather";
import FontAwesome from "@expo/vector-icons/FontAwesome";
import * as Sentry from "@sentry/react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { twMerge } from "tailwind-merge";

import type { PitcherSubscription } from "@probable/ui/utils";
import { subscriptionSchedule } from "@probable/ui/utils";

import Card from "~/components/Card";
import PressableThemed from "~/components/PressableThemed";
import SearchInput from "~/components/SearchInput";
import { AnimatedViewStyled } from "~/components/Styled";
import { trpc } from "~/utils/api";

export default function Home() {
  const queryClient = useQueryClient();
  const router = useRouter();

  const subscriptionQuery = useQuery(trpc.subscription.byUserId.queryOptions());

  useEffect(() => {
    if (subscriptionQuery.isFetched) {
      SplashScreen.hide();
    }
  }, [subscriptionQuery.isFetched]);

  if (subscriptionQuery.isError) {
    throw new Error(
      `Error fetching subscriptions: ${JSON.stringify(subscriptionQuery.error)}`,
    );
  }

  const schedule = subscriptionSchedule(subscriptionQuery.data);

  const [searchFilter, setSearchFilter] = useState<string>();
  const [isSearchActive, setIsSearchActive] = useState<boolean>(false);

  const searchQuery = useQuery(
    trpc.pitcher.byFuzzyName.queryOptions(searchFilter ?? "", {
      enabled: !!searchFilter && subscriptionQuery.isSuccess,
    }),
  );

  if (searchQuery.isError) {
    Sentry.captureException(
      `Error fuzzy searching for pitchers on homepage: ${JSON.stringify(searchQuery.error)}`,
    );
  }

  const pitchers = searchQuery.data?.map((pitcher) => ({
    ...pitcher,
    subscription:
      subscriptionQuery.data?.find((sub) => sub.pitcherId === pitcher.id) ??
      undefined,
  }));

  const subscribeMutation = useMutation(
    trpc.subscription.create.mutationOptions({
      scope: { id: "subscription" },
      onMutate: async ({ pitcherId }) => {
        await queryClient.cancelQueries(
          trpc.subscription.byUserId.pathFilter(),
        );
        const previousSubscriptions = queryClient.getQueryData(
          trpc.subscription.byUserId.queryKey(),
        );
        queryClient.setQueryData(
          trpc.subscription.byUserId.queryKey(),
          (old) => {
            if (old) {
              const pitcher = pitchers?.find((p) => p.id === pitcherId);
              if (pitcher) {
                return [
                  ...old,
                  // Optimistically add a new subscription with some dummy data.
                  // This dummy data will be replaced with ids generated by the
                  // database once the mutation completes.
                  {
                    id: String(new Date().valueOf()),
                    enabled: true,
                    pitcherId: pitcher.id,
                    userId: "",
                    pitcher: {
                      id: pitcher.id,
                      name: pitcher.name,
                      teamId: pitcher.teamId,
                      homeGames: pitcher.subscription?.pitcher.homeGames ?? [],
                      awayGames: pitcher.subscription?.pitcher.awayGames ?? [],
                      number: pitcher.number,
                      team: {
                        name: "",
                        id: "",
                        abbreviation: pitcher.teamAbbreviation,
                      },
                      gone: pitcher.gone,
                      active: pitcher.active,
                    },
                  },
                ];
              }
            }
          },
        );
        return { previousSubscriptions };
      },
      onError: (err, _, context) => {
        queryClient.setQueryData(
          trpc.subscription.byUserId.queryKey(),
          context?.previousSubscriptions,
        );
        Sentry.captureException(err);
      },
      onSettled: () => {
        queryClient
          .invalidateQueries(trpc.subscription.byUserId.pathFilter())
          .catch(Sentry.captureException);
        queryClient
          .invalidateQueries(trpc.pitcher.byFuzzyName.pathFilter())
          .catch(Sentry.captureException);
      },
    }),
  );

  const unsubscribeMutation = useMutation(
    trpc.subscription.delete.mutationOptions({
      scope: { id: "subscription" },
      onMutate: async ({ subscriptionId }) => {
        await queryClient.cancelQueries(
          trpc.subscription.byUserId.pathFilter(),
        );
        const previousSubscriptions = queryClient.getQueryData(
          trpc.subscription.byUserId.queryKey(),
        );
        queryClient.setQueryData(trpc.subscription.byUserId.queryKey(), (old) =>
          old?.filter((s) => s.id !== subscriptionId),
        );
        return { previousSubscriptions };
      },
      onError: (err, _, context) => {
        queryClient.setQueryData(
          trpc.subscription.byUserId.queryKey(),
          context?.previousSubscriptions,
        );
        Sentry.captureException(err);
      },
      onSettled: () => {
        queryClient
          .invalidateQueries(trpc.subscription.byUserId.pathFilter())
          .catch(Sentry.captureException);
        queryClient
          .invalidateQueries(trpc.pitcher.byFuzzyName.pathFilter())
          .catch(Sentry.captureException);
      },
    }),
  );

  // Why not just use section list? It doesn't have support from Reanimated's "itemLayoutAnimation"
  // prop, which we are depending on below for the cool layout transitions.
  const subscribedAndAvailablePitchers: (string | PitcherSubscription)[] = [];

  if (isSearchActive) {
    if (subscriptionQuery.data) {
      const subscribedPitchers =
        pitchers
          ?.filter((p) => p.subscription)
          .map((p) => ({
            ...p,
            team: {
              abbreviation: p.teamAbbreviation ?? null,
            },
          })) ?? [];
      if (subscribedPitchers.length) {
        subscribedAndAvailablePitchers.push("Subscribed");
        subscribedAndAvailablePitchers.push(...subscribedPitchers);
      }
    }

    if (searchFilter) {
      const availablePitchers =
        pitchers
          ?.filter((p) => !p.subscription)
          .map((p) => ({
            ...p,
            team: {
              abbreviation: p.teamAbbreviation ?? null,
            },
          })) ?? [];
      if (availablePitchers.length) {
        subscribedAndAvailablePitchers.push("Available");
        subscribedAndAvailablePitchers.push(...availablePitchers);
      }
    }
  } else {
    schedule.map((day) => {
      subscribedAndAvailablePitchers.push(day.nextGameDay);
      subscribedAndAvailablePitchers.push(...day.data);
    });
  }

  const pauseMutations =
    subscribeMutation.isPending ||
    unsubscribeMutation.isPending ||
    searchQuery.isFetching ||
    (!searchQuery.isSuccess && !!searchFilter) ||
    subscriptionQuery.isFetching;

  const opacity = useSharedValue(1);

  useEffect(() => {
    opacity.value = withTiming(pauseMutations ? 0.4 : 1, {
      duration: 150,
      easing: Easing.linear,
    });
  }, [opacity, pauseMutations]);

  const style = useAnimatedStyle(() => ({ opacity: opacity.value }), []);

  const [isEditing, setIsEditing] = useState(false);

  useEffect(() => {
    if (isSearchActive) setIsEditing(false);
  }, [isSearchActive]);

  const [isManualRefreshing, setIsManualRefreshing] = useState(false);

  const insets = useSafeAreaInsets();

  if (subscriptionQuery.isPending) {
    return (
      <View className="bg-background flex-1">
        <Stack.Screen options={{ headerShown: false }} />
        <ActivityIndicator
          className={`text-foreground absolute m-auto h-full w-full`}
          size="large"
        />
      </View>
    );
  }

  return (
    <View className="bg-background flex-1">
      <Stack.Screen
        options={{
          headerShown: !isSearchActive || Platform.OS === "android",
          headerLeft:
            Platform.OS === "ios" || !isSearchActive
              ? () => (
                  <AnimatedViewStyled
                    entering={FadeInUp.duration(200)}
                    exiting={FadeOutUp.duration(200)}
                    className="-ml-3 h-12 w-12 flex-row items-center justify-start"
                  >
                    <PressableThemed
                      onPress={() => {
                        Keyboard.dismiss();
                        setIsEditing(false);
                        router.navigate("/settings");
                      }}
                      accessibilityLabel="Navigate to Application Settings"
                      className="h-full w-full items-start justify-center pl-2"
                    >
                      <Text
                        className="text-primary"
                        maxFontSizeMultiplier={1.2}
                      >
                        <Feather name="settings" size={22} />
                      </Text>
                    </PressableThemed>
                  </AnimatedViewStyled>
                )
              : undefined,
          headerRight: () =>
            !isSearchActive && (
              <AnimatedViewStyled
                entering={FadeInUp.duration(200)}
                exiting={FadeOutUp.duration(200)}
                className="-mr-3 h-12 w-20 flex-row items-center justify-end"
              >
                <PressableThemed
                  onPress={() => {
                    Keyboard.dismiss();
                    setIsEditing((isEditing) => !isEditing);
                  }}
                  className="h-full w-full items-end justify-center pr-2"
                  accessibilityLabel={
                    isEditing ? "Disable edit mode" : "Enable edit mode"
                  }
                >
                  {!!subscriptionQuery.data.length &&
                    (isEditing ? (
                      <Animated.View
                        entering={FadeInRight.duration(200)}
                        exiting={FadeOutRight.duration(100)}
                      >
                        <Text
                          className="text-primary text-xl font-bold"
                          maxFontSizeMultiplier={1.15}
                        >
                          Done
                        </Text>
                      </Animated.View>
                    ) : (
                      <Animated.View
                        entering={FadeIn.duration(200)}
                        exiting={FadeOut.duration(100)}
                      >
                        <Text
                          className="text-primary text-xl"
                          maxFontSizeMultiplier={1.15}
                        >
                          Edit
                        </Text>
                      </Animated.View>
                    ))}
                </PressableThemed>
              </AnimatedViewStyled>
            ),
        }}
      />
      {/* TODO: use more performant list. Improve animations when subscriber list is huge */}
      <Animated.FlatList
        entering={FadeIn}
        layout={LinearTransition.duration(400)}
        refreshControl={
          // Android rerenders and causes bugs with the keyboard when the Search Input focus events toggle the control
          !isSearchActive || Platform.OS === "android" ? (
            <RefreshControl
              refreshing={isManualRefreshing}
              onRefresh={async () => {
                setIsManualRefreshing(true);
                try {
                  await queryClient.refetchQueries(
                    trpc.subscription.byUserId.pathFilter(),
                  );
                } catch (e) {
                  Sentry.captureException(e);
                } finally {
                  setIsManualRefreshing(false);
                }
              }}
              enabled={!isSearchActive}
            />
          ) : (
            <React.Fragment />
          )
        }
        itemLayoutAnimation={LinearTransition.duration(175)}
        keyExtractor={(item) => {
          if (typeof item === "string") {
            return item;
          }
          return String(item.id);
        }}
        contentContainerStyle={{ paddingBottom: isSearchActive ? 384 : 192 }}
        data={subscribedAndAvailablePitchers}
        keyboardShouldPersistTaps="handled"
        stickyHeaderIndices={[0]}
        stickyHeaderHiddenOnScroll={!isSearchActive}
        ListHeaderComponent={
          <AnimatedViewStyled
            layout={LinearTransition.duration(200)}
            className="bg-background/80 mb-3"
          >
            <View style={{ paddingTop: isSearchActive ? insets.top : 0 }}>
              {!isSearchActive && (
                <AnimatedViewStyled
                  entering={FadeIn.duration(500)}
                  exiting={FadeOut.duration(100)}
                  layout={LinearTransition}
                  className={twMerge("android:mt-6 mt-8", "mb-3 pl-3")}
                >
                  <Text
                    className={twMerge(
                      "text-foreground text-4xl font-bold tracking-tight",
                    )}
                    maxFontSizeMultiplier={1.5}
                    accessibilityRole="header"
                  >
                    Probable Pitcher
                  </Text>
                </AnimatedViewStyled>
              )}
            </View>
            <AnimatedViewStyled layout={LinearTransition} className="mx-3">
              <SearchInput
                onChange={(text) => setSearchFilter(text ?? "")}
                onActive={() => setIsSearchActive(true)}
                onCancel={() => setIsSearchActive(false)}
              />
            </AnimatedViewStyled>
          </AnimatedViewStyled>
        }
        renderItem={({ index, item }) => {
          if (typeof item === "string") {
            return (
              <AnimatedViewStyled
                entering={FadeIn}
                exiting={FadeOut}
                className="mx-6 mb-1"
              >
                <Text
                  maxFontSizeMultiplier={2}
                  className="text-muted text-base uppercase"
                >
                  {item}
                </Text>
              </AnimatedViewStyled>
            );
          } else {
            return (
              <AnimatedViewStyled entering={FadeIn} exiting={FadeOut}>
                <PitcherCard
                  subscribeHandler={() => {
                    if (item.id) {
                      subscribeMutation.mutate({
                        pitcherId: item.id,
                      });
                    }
                  }}
                  unsubscribeHandler={
                    isEditing || isSearchActive
                      ? () =>
                          item.subscription
                            ? unsubscribeMutation.mutate({
                                subscriptionId: item.subscription.id,
                              })
                            : undefined
                      : undefined
                  }
                  pitcher={item}
                  disabled={pauseMutations}
                  className={twMerge(
                    "border-border rounded-none border-b-1",
                    typeof subscribedAndAvailablePitchers[index - 1] ===
                      "string"
                      ? "rounded-t-lg"
                      : null,
                    !subscribedAndAvailablePitchers[index + 1] ||
                      typeof subscribedAndAvailablePitchers[index + 1] ===
                        "string"
                      ? "mb-3 rounded-b-lg border-b-0"
                      : null,
                  )}
                  buttonStyle={style}
                />
              </AnimatedViewStyled>
            );
          }
        }}
        ListEmptyComponent={
          <View>
            {searchQuery.isFetching ? (
              <AnimatedViewStyled entering={FadeIn} exiting={FadeOut}>
                <ActivityIndicator className="text-muted top-9" size="large" />
              </AnimatedViewStyled>
            ) : searchQuery.isSuccess ? (
              <AnimatedViewStyled
                entering={FadeIn.delay(150)}
                exiting={FadeOut}
              >
                <Text
                  className="text-muted mx-6 mb-6 text-base"
                  accessibilityRole="summary"
                  maxFontSizeMultiplier={1.5}
                >
                  No pitchers found, try changing your search
                </Text>
              </AnimatedViewStyled>
            ) : searchQuery.isError ? (
              <AnimatedViewStyled
                entering={FadeIn.delay(150)}
                exiting={FadeOut}
              >
                <Text
                  className="text-destructive mx-6 mb-6 text-base"
                  accessibilityRole="alert"
                  maxFontSizeMultiplier={1.5}
                >
                  An error occurred while performing your search, please try
                  again later
                </Text>
              </AnimatedViewStyled>
            ) : (
              <AnimatedViewStyled
                layout={LinearTransition.duration(200)}
                entering={FadeIn}
                exiting={FadeOut}
              >
                <Text
                  className="text-muted mx-6 mb-6 text-base"
                  accessibilityRole="summary"
                  maxFontSizeMultiplier={1.5}
                >
                  Search for your favorite pitcher to add them to your list of
                  subscriptions
                </Text>
              </AnimatedViewStyled>
            )}
          </View>
        }
      />
    </View>
  );
}

const PitcherCard = ({
  subscribeHandler,
  unsubscribeHandler,
  pitcher,
  disabled,
  className,
  buttonStyle,
}: {
  subscribeHandler: () => void;
  unsubscribeHandler?: () => void;
  pitcher: PitcherSubscription;
  disabled?: boolean;
  className?: string;
  buttonStyle: StyleProp<AnimatedStyle<StyleProp<ViewStyle>>>;
}) => {
  return (
    <Card className={twMerge("relative", className)}>
      {pitcher.subscription && unsubscribeHandler && (
        <AnimatedViewStyled entering={FadeInLeft} exiting={FadeOutLeft}>
          <PressableThemed
            className="-my-3 -mr-1 -ml-3 p-3"
            onPress={unsubscribeHandler}
            accessibilityLabel={""}
            disabled={disabled}
          >
            <AnimatedViewStyled style={buttonStyle}>
              <Text maxFontSizeMultiplier={2.5} className="text-destructive">
                <FontAwesome name="minus-circle" size={18} />
              </Text>
            </AnimatedViewStyled>
          </PressableThemed>
        </AnimatedViewStyled>
      )}
      <AnimatedViewStyled
        className="flex-1 flex-row flex-wrap items-center justify-between"
        layout={LinearTransition}
      >
        <AnimatedViewStyled
          className="shrink flex-row items-center"
          layout={LinearTransition}
        >
          <Text
            maxFontSizeMultiplier={2.5}
            className="text-foreground shrink text-xl"
          >
            {pitcher.name}
          </Text>
          <View className="mx-3 -my-1.5 items-center">
            {pitcher.number && (
              <Text
                maxFontSizeMultiplier={2.5}
                className="text-muted -mb-0.5 text-sm leading-none"
              >
                {pitcher.number}
              </Text>
            )}
            <Text
              maxFontSizeMultiplier={2.5}
              className="text-muted text-sm leading-none tracking-tight"
            >
              {pitcher.team.abbreviation}
            </Text>
          </View>
        </AnimatedViewStyled>
        {pitcher.nextGameDate && !unsubscribeHandler && (
          <AnimatedViewStyled
            entering={FadeInRight}
            exiting={FadeOutRight}
            layout={LinearTransition}
          >
            <Text
              maxFontSizeMultiplier={2.5}
              className="text-muted ml-1.5 text-base tracking-tight"
            >
              {new TZDate(
                pitcher.nextGameDate,
                Intl.DateTimeFormat().resolvedOptions().timeZone ||
                  "America/New_York",
              )
                .toLocaleTimeString([], {
                  hour: "numeric",
                  minute: "2-digit",
                  hour12: true,
                })
                .toLowerCase()
                .replace("m", "")}
            </Text>
          </AnimatedViewStyled>
        )}
      </AnimatedViewStyled>
      {!pitcher.subscription && (
        <PressableThemed
          className="-my-3 -mr-6 p-3"
          onPress={subscribeHandler}
          accessibilityLabel={""}
          disabled={disabled}
        >
          <AnimatedViewStyled style={buttonStyle}>
            <Text maxFontSizeMultiplier={2.5} className="text-primary pr-3">
              <FontAwesome
                className="text-primary"
                name="plus-circle"
                size={18}
              />
            </Text>
          </AnimatedViewStyled>
        </PressableThemed>
      )}
    </Card>
  );
};
