name: Integrate and Deploy Main to Preview
on:
  push:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  changeset:
    name: Changeset
    runs-on: ubuntu-latest
    outputs:
      changed-nextjs: ${{ steps.changed-nextjs.outputs.result }}
      changed-ingest: ${{ steps.changed-ingest.outputs.result }}
      changed-expo: ${{ steps.changed-expo.outputs.result }}
      changed-db: ${{ steps.changed-db.outputs.result }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.3
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Create Changeset
        id: changeset
        run: |
          content=`pnpm run --silent build --filter=...\[preview\] --dry-run=json`
          content="${content//$'\n'/''}"
          content="${content//$'\r'/''}"
          echo "result=$content" >> "$GITHUB_OUTPUT"

      - name: Changed nextjs?
        id: changed-nextjs
        if: ${{ contains(fromJSON(steps.changeset.outputs.result).packages, '@probable/nextjs') }}
        run: |
          echo "result=true" >> "$GITHUB_OUTPUT"

      - name: Changed ingest?
        id: changed-ingest
        if: ${{ contains(fromJSON(steps.changeset.outputs.result).packages, '@probable/ingest') }}
        run: |
          echo "result=true" >> "$GITHUB_OUTPUT"

      - name: Changed expo?
        id: changed-expo
        if: ${{ contains(fromJSON(steps.changeset.outputs.result).packages, '@probable/expo') }}
        run: |
          echo "result=true" >> "$GITHUB_OUTPUT"

      - name: Changed db?
        id: changed-db
        if: ${{ contains(fromJSON(steps.changeset.outputs.result).packages, '@probable/db') }}
        run: |
          echo "result=true" >> "$GITHUB_OUTPUT"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run integration tests using Docker Compose
        run: |
          BETTER_AUTH_URL=http://localhost:3000 \
          BETTER_AUTH_SECRET=secret \
          AUTH_GOOGLE_ID=secret \
          AUTH_GOOGLE_SECRET=secret \
          AUTH_APPLE_BUNDLE_ID=secret \
          AUTH_APPLE_SERVICE_ID=secret \
          AUTH_APPLE_SECRET=secret \
          AUTH_APPLE_WEB_ID=secret \
          AUTH_APPLE_WEB_SECRET=secret \
          docker compose up --abort-on-container-failure integration stress

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.3
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint Checker
        run: pnpm lint

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.3
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Format Checker
        run: pnpm format

  build-nextjs:
    name: Build nextjs image
    needs: [test, lint, format, changeset]
    runs-on: ubuntu-latest
    if: ${{ needs.changeset.outputs.changed-nextjs }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Build and publish nextjs image
        run: |
          docker build . --file apps/nextjs/Dockerfile --tag ghcr.io/tmlamb/probable-nextjs:sha-${{ github.sha }} --tag ghcr.io/tmlamb/probable-nextjs:latest --build-arg TURBO_TEAM=${{ env.TURBO_TEAM }} --build-arg TURBO_TOKEN=${{ env.TURBO_TOKEN }}
          docker push --all-tags ghcr.io/tmlamb/probable-nextjs

  build-ingest:
    name: Build ingest image
    needs: [test, lint, format, changeset]
    runs-on: ubuntu-latest
    if: ${{ needs.changeset.outputs.changed-ingest }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Build and publish ingest image
        run: |
          docker build . --file apps/ingest/Dockerfile --tag ghcr.io/tmlamb/probable-ingest:sha-${{ github.sha }} --tag ghcr.io/tmlamb/probable-ingest:latest --build-arg TURBO_TEAM=${{ env.TURBO_TEAM }} --build-arg TURBO_TOKEN=${{ env.TURBO_TOKEN }}
          docker push --all-tags ghcr.io/tmlamb/probable-ingest

  build-migration:
    name: Build Migration image
    needs: [test, lint, format, changeset]
    runs-on: ubuntu-latest
    if: ${{ needs.changeset.outputs.changed-db }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Build and publish db migration image
        run: |
          docker build . --file packages/db/Dockerfile --tag ghcr.io/tmlamb/probable-migration:sha-${{ github.sha }} --tag ghcr.io/tmlamb/probable-migration:latest --build-arg TURBO_TEAM=${{ env.TURBO_TEAM }} --build-arg TURBO_TOKEN=${{ env.TURBO_TOKEN }}
          docker push --all-tags ghcr.io/tmlamb/probable-migration

  deploy-infra:
    name: Deploy Preview Infrastructure
    needs:
      [
        test,
        format,
        lint,
        changeset,
        build-nextjs,
        build-ingest,
        build-migration,
      ]
    if: always() &&
      (needs.test.result == 'success' && needs.format.result == 'success' && needs.lint.result == 'success') &&
      (needs.build-migration.result == 'skipped' || needs.build-migration.result == 'success') &&
      (needs.build-nextjs.result == 'skipped' || needs.build-nextjs.result == 'success') &&
      (needs.build-ingest.result == 'skipped' || needs.build-ingest.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.3
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_PROD }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKR Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: probable-pitcher
          location: us-west1

      - name: Install Dependencies
        run: pnpm install

      - name: Update test stack
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: preview
          work-dir: infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DEPLOY_COMMIT_TAG: sha-${{ github.sha }}
          CHANGED_INGEST: ${{ needs.changeset.outputs.changed-ingest }}
          CHANGED_NEXTJS: ${{ needs.changeset.outputs.changed-nextjs }}
          CHANGED_DB: ${{ needs.changeset.outputs.changed-db }}

  update-preview:
    name: Update Preview Mobile App
    needs: [test, format, lint, changeset, deploy-infra]
    if: |
      always() &&
      needs.changeset.result == 'success' &&
      (needs.test.result == 'success' && needs.format.result == 'success' && needs.lint.result == 'success') &&
      (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped') &&
      needs.changeset.outputs.changed-expo
    runs-on: ubuntu-latest
    env:
      CHANGED_EXPO: ${{ needs.changeset.outputs.changed-expo }}
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.3
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: pnpm install

      - name: Publish Live App Update
        run: cd apps/expo && APP_ENV=preview BETTER_AUTH_URL="https://dev.probablepitcher.com" eas update --environment preview --branch preview --message "${{ github.event.head_commit.id }}"

  tag-git:
    name: Preview Tag Git
    needs: [deploy-infra, update-preview]
    if: always() &&
      needs.deploy-infra.result == 'success' || needs.update-preview.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@v4

      - name: "Push preview tag"
        uses: EndBug/latest-tag@latest
        with:
          ref: preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
