name: Integrate Pull Request
on:
  - push

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Start application-specific services using Docker Compose
        run: AUTH_SECRET=secret AUTH_GOOGLE_ID=secret AUTH_GOOGLE_SECRET=secret AUTH_APPLE_ID=secret AUTH_APPLE_SECRET=secret docker compose up --abort-on-container-failure integration stress

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.2
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint Checker
        run: pnpm lint

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.2
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Format Checker
        run: pnpm format

  # dry-run-infra:
  #   name: Infra Deploy Dry-run
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4
  #     - name: Setup pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: 9
  #         run_install: false
  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 23
  #         cache: "pnpm"
  #
  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v1
  #       with:
  #         credentials_json: "${{ secrets.GCP_CREDENTIALS_PROD }}"
  #
  #     - name: "Set up Cloud SDK"
  #       uses: "google-github-actions/setup-gcloud@v1"
  #
  #     - name: "Get GKR Credentials"
  #       uses: "google-github-actions/get-gke-credentials@v1"
  #       with:
  #         cluster_name: "probable-pitcher"
  #         location: "us-west1"
  #
  #     - name: Install Dependencies
  #       run: cd infrastructure && npm ci
  #
  #     - name: Preview Test Stack
  #       uses: pulumi/actions@v4
  #       with:
  #         command: preview
  #         stack-name: preview
  #         work-dir: infrastructure
  #       env:
  #         PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
